import { StorageEnum } from '../base/enums';
import { createStorage } from '../base/base';
import type { BaseStorage } from '../base/types';

type BackgroundData = {
  lastUpdate: number;
  counter: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  etrProjections: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  pickSixSlates: any;
};

const ETR_COPY_PASTE = [
  {
    Player: 'Luka Doncic',
    Position: 'PG',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 37,
    Points: 27.1,
    Assists: 8.2,
    Rebounds: 8.5,
    ThreePt: 2.95,
    Turnovers: 3.5,
    Steals: 1.3,
    Blocks: 0.42,
  },
  {
    Player: 'Nikola Jokic',
    Position: 'C',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 35.5,
    Points: 25.9,
    Assists: 8.8,
    Rebounds: 11.5,
    ThreePt: 1.39,
    Turnovers: 2.77,
    Steals: 1.31,
    Blocks: 0.85,
  },
  {
    Player: 'Anthony Edwards',
    Position: 'SG/SF',
    Team: 'MIN',
    Opponent: 'DAL',
    Minutes: 37.5,
    Points: 25.8,
    Assists: 5.7,
    Rebounds: 5.6,
    ThreePt: 3.34,
    Turnovers: 2.93,
    Steals: 1.35,
    Blocks: 0.6,
  },
  {
    Player: 'Cam Thomas',
    Position: 'SG/PG',
    Team: 'BKN',
    Opponent: 'DEN',
    Minutes: 34.5,
    Points: 25.4,
    Assists: 4.1,
    Rebounds: 3.8,
    ThreePt: 2.73,
    Turnovers: 1.93,
    Steals: 0.88,
    Blocks: 0.23,
  },
  {
    Player: "De'Aaron Fox",
    Position: 'PG',
    Team: 'SAC',
    Opponent: 'UTA',
    Minutes: 36,
    Points: 24.3,
    Assists: 5.7,
    Rebounds: 4.5,
    ThreePt: 2.73,
    Turnovers: 2.44,
    Steals: 1.92,
    Blocks: 0.46,
  },
  {
    Player: 'Zion Williamson',
    Position: 'PF',
    Team: 'NOP',
    Opponent: 'GSW',
    Minutes: 31,
    Points: 22.8,
    Assists: 5,
    Rebounds: 6.5,
    ThreePt: 0.15,
    Turnovers: 2.67,
    Steals: 1.02,
    Blocks: 0.84,
  },
  {
    Player: 'Lauri Markkanen',
    Position: 'PF/SF',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 34,
    Points: 22.7,
    Assists: 2.4,
    Rebounds: 8.1,
    ThreePt: 3.17,
    Turnovers: 1.6,
    Steals: 0.71,
    Blocks: 0.45,
  },
  {
    Player: 'DeMar DeRozan',
    Position: 'SF/PF',
    Team: 'SAC',
    Opponent: 'UTA',
    Minutes: 36,
    Points: 22.5,
    Assists: 4.3,
    Rebounds: 4.4,
    ThreePt: 0.83,
    Turnovers: 1.81,
    Steals: 1.24,
    Blocks: 0.54,
  },
  {
    Player: 'C.J. McCollum',
    Position: 'SG/PG',
    Team: 'NOP',
    Opponent: 'GSW',
    Minutes: 36,
    Points: 21.8,
    Assists: 4.8,
    Rebounds: 4.8,
    ThreePt: 3.82,
    Turnovers: 1.86,
    Steals: 1.1,
    Blocks: 0.53,
  },
  {
    Player: 'Kyrie Irving',
    Position: 'SG/PG',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 34,
    Points: 20,
    Assists: 4.6,
    Rebounds: 4.2,
    ThreePt: 2.2,
    Turnovers: 1.61,
    Steals: 1.16,
    Blocks: 0.4,
  },
  {
    Player: 'Julius Randle',
    Position: 'PF',
    Team: 'MIN',
    Opponent: 'DAL',
    Minutes: 34,
    Points: 19.6,
    Assists: 5,
    Rebounds: 7.9,
    ThreePt: 1.47,
    Turnovers: 2.67,
    Steals: 0.62,
    Blocks: 0.3,
  },
  {
    Player: 'Brandon Ingram',
    Position: 'SF/PF',
    Team: 'NOP',
    Opponent: 'GSW',
    Minutes: 34,
    Points: 19,
    Assists: 4.8,
    Rebounds: 6.4,
    ThreePt: 1.29,
    Turnovers: 2.37,
    Steals: 0.87,
    Blocks: 0.56,
  },
  {
    Player: 'Jamal Murray',
    Position: 'PG',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 34,
    Points: 18.7,
    Assists: 5.5,
    Rebounds: 3.9,
    ThreePt: 2.36,
    Turnovers: 1.93,
    Steals: 1.06,
    Blocks: 0.54,
  },
  {
    Player: 'Domantas Sabonis',
    Position: 'C/PF',
    Team: 'SAC',
    Opponent: 'UTA',
    Minutes: 36,
    Points: 18.6,
    Assists: 7.4,
    Rebounds: 13.5,
    ThreePt: 0.48,
    Turnovers: 2.78,
    Steals: 0.88,
    Blocks: 0.61,
  },
  {
    Player: 'Buddy Hield',
    Position: 'SG/PG',
    Team: 'GSW',
    Opponent: 'NOP',
    Minutes: 31,
    Points: 18.2,
    Assists: 3.2,
    Rebounds: 3.7,
    ThreePt: 4.02,
    Turnovers: 1.88,
    Steals: 0.99,
    Blocks: 0.48,
  },
  {
    Player: 'Michael Porter Jr.',
    Position: 'SF/PF',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 34,
    Points: 16.2,
    Assists: 1.8,
    Rebounds: 6.9,
    ThreePt: 2.7,
    Turnovers: 1.1,
    Steals: 0.62,
    Blocks: 0.56,
  },
  {
    Player: 'Keegan Murray',
    Position: 'PF/SF',
    Team: 'SAC',
    Opponent: 'UTA',
    Minutes: 36,
    Points: 16.2,
    Assists: 1.7,
    Rebounds: 5.7,
    ThreePt: 3.02,
    Turnovers: 0.87,
    Steals: 1.13,
    Blocks: 0.89,
  },
  {
    Player: 'Jonathan Kuminga',
    Position: 'PF/SF',
    Team: 'GSW',
    Opponent: 'NOP',
    Minutes: 25.5,
    Points: 16,
    Assists: 2,
    Rebounds: 4.3,
    ThreePt: 0.81,
    Turnovers: 1.94,
    Steals: 0.63,
    Blocks: 0.54,
  },
  {
    Player: 'Keyonte George',
    Position: 'PG/SG',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 32,
    Points: 15.8,
    Assists: 5.5,
    Rebounds: 3.4,
    ThreePt: 2.28,
    Turnovers: 2.52,
    Steals: 0.79,
    Blocks: 0.16,
  },
  {
    Player: 'Dennis Schroder',
    Position: 'PG',
    Team: 'BKN',
    Opponent: 'DEN',
    Minutes: 33.5,
    Points: 15.6,
    Assists: 7,
    Rebounds: 3.6,
    ThreePt: 1.92,
    Turnovers: 2.43,
    Steals: 0.86,
    Blocks: 0.21,
  },
  {
    Player: 'Jordan Clarkson',
    Position: 'PG/SG',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 28,
    Points: 15.3,
    Assists: 4.7,
    Rebounds: 3.2,
    ThreePt: 1.61,
    Turnovers: 2.27,
    Steals: 0.66,
    Blocks: 0.16,
  },
  {
    Player: 'Collin Sexton',
    Position: 'SG/PG',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 25,
    Points: 15.3,
    Assists: 4.9,
    Rebounds: 2.4,
    ThreePt: 1.31,
    Turnovers: 1.88,
    Steals: 0.76,
    Blocks: 0.16,
  },
  {
    Player: 'Cameron Johnson',
    Position: 'SF/PF',
    Team: 'BKN',
    Opponent: 'DEN',
    Minutes: 32,
    Points: 15.1,
    Assists: 2.7,
    Rebounds: 4.8,
    ThreePt: 2.75,
    Turnovers: 1.09,
    Steals: 1.04,
    Blocks: 0.36,
  },
  {
    Player: 'Klay Thompson',
    Position: 'SF/SG',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 29,
    Points: 14.6,
    Assists: 1.3,
    Rebounds: 3.2,
    ThreePt: 3.03,
    Turnovers: 1.45,
    Steals: 0.63,
    Blocks: 0.33,
  },
  {
    Player: 'Malik Monk',
    Position: 'SG/PG',
    Team: 'SAC',
    Opponent: 'UTA',
    Minutes: 25,
    Points: 14.1,
    Assists: 3.9,
    Rebounds: 2.9,
    ThreePt: 2.02,
    Turnovers: 1.76,
    Steals: 0.73,
    Blocks: 0.47,
  },
  {
    Player: 'Moses Moody',
    Position: 'SG',
    Team: 'GSW',
    Opponent: 'NOP',
    Minutes: 26,
    Points: 13.7,
    Assists: 1.5,
    Rebounds: 3.4,
    ThreePt: 2.42,
    Turnovers: 1.21,
    Steals: 0.72,
    Blocks: 0.38,
  },
  {
    Player: 'Aaron Gordon',
    Position: 'PF',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 34,
    Points: 13.5,
    Assists: 3.5,
    Rebounds: 6.1,
    ThreePt: 0.64,
    Turnovers: 1.51,
    Steals: 0.83,
    Blocks: 0.71,
  },
  {
    Player: 'Donte DiVincenzo',
    Position: 'SF/SG',
    Team: 'MIN',
    Opponent: 'DAL',
    Minutes: 26.5,
    Points: 12.7,
    Assists: 2.8,
    Rebounds: 3.5,
    ThreePt: 2.74,
    Turnovers: 1.24,
    Steals: 1.08,
    Blocks: 0.28,
  },
  {
    Player: 'Naz Reid',
    Position: 'C/PF',
    Team: 'MIN',
    Opponent: 'DAL',
    Minutes: 25.5,
    Points: 12.6,
    Assists: 1.8,
    Rebounds: 5.5,
    ThreePt: 1.75,
    Turnovers: 1.31,
    Steals: 0.76,
    Blocks: 0.99,
  },
  {
    Player: 'Rudy Gobert',
    Position: 'C',
    Team: 'MIN',
    Opponent: 'DAL',
    Minutes: 34,
    Points: 12.5,
    Assists: 1.6,
    Rebounds: 12.4,
    ThreePt: 0.01,
    Turnovers: 1.49,
    Steals: 0.73,
    Blocks: 1.98,
  },
  {
    Player: 'John Collins',
    Position: 'PF/C',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 22.5,
    Points: 12.5,
    Assists: 1.2,
    Rebounds: 6.5,
    ThreePt: 1.03,
    Turnovers: 1.15,
    Steals: 0.44,
    Blocks: 0.64,
  },
  {
    Player: 'Brandin Podziemski',
    Position: 'SG/PG',
    Team: 'GSW',
    Opponent: 'NOP',
    Minutes: 31,
    Points: 12,
    Assists: 4.8,
    Rebounds: 5.8,
    ThreePt: 1.87,
    Turnovers: 1.95,
    Steals: 0.85,
    Blocks: 0.21,
  },
  {
    Player: 'Jordan Hawkins',
    Position: 'SG',
    Team: 'NOP',
    Opponent: 'GSW',
    Minutes: 30,
    Points: 12,
    Assists: 1.7,
    Rebounds: 3.9,
    ThreePt: 2.43,
    Turnovers: 1.05,
    Steals: 0.52,
    Blocks: 0.24,
  },
  {
    Player: 'Trayce Jackson-Davis',
    Position: 'C/PF',
    Team: 'GSW',
    Opponent: 'NOP',
    Minutes: 24,
    Points: 11.7,
    Assists: 1.8,
    Rebounds: 6.7,
    ThreePt: 0.01,
    Turnovers: 1.2,
    Steals: 0.6,
    Blocks: 1.65,
  },
  {
    Player: 'Christian Braun',
    Position: 'SG/SF',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 32.5,
    Points: 10.8,
    Assists: 1.7,
    Rebounds: 4.8,
    ThreePt: 1.22,
    Turnovers: 1.09,
    Steals: 0.88,
    Blocks: 0.53,
  },
  {
    Player: 'Kevin Huerter',
    Position: 'SG/SF',
    Team: 'SAC',
    Opponent: 'UTA',
    Minutes: 25,
    Points: 10.4,
    Assists: 2.4,
    Rebounds: 3.2,
    ThreePt: 2.1,
    Turnovers: 0.91,
    Steals: 0.85,
    Blocks: 0.38,
  },
  {
    Player: 'Jaden McDaniels',
    Position: 'SF/PF',
    Team: 'MIN',
    Opponent: 'DAL',
    Minutes: 28.5,
    Points: 10.3,
    Assists: 1.9,
    Rebounds: 3.3,
    ThreePt: 1.18,
    Turnovers: 1.12,
    Steals: 0.8,
    Blocks: 0.59,
  },
  {
    Player: 'P.J. Washington',
    Position: 'PF',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 31,
    Points: 10.2,
    Assists: 1.3,
    Rebounds: 5.7,
    ThreePt: 1.52,
    Turnovers: 1.06,
    Steals: 0.9,
    Blocks: 0.78,
  },
  {
    Player: 'Herbert Jones',
    Position: 'PF/SF',
    Team: 'NOP',
    Opponent: 'GSW',
    Minutes: 33,
    Points: 9.8,
    Assists: 2.5,
    Rebounds: 4.3,
    ThreePt: 1.34,
    Turnovers: 1.26,
    Steals: 1.64,
    Blocks: 0.75,
  },
  {
    Player: 'Noah Clowney',
    Position: 'PF/C',
    Team: 'BKN',
    Opponent: 'DEN',
    Minutes: 25,
    Points: 9.8,
    Assists: 1.3,
    Rebounds: 6.5,
    ThreePt: 0.89,
    Turnovers: 1,
    Steals: 0.58,
    Blocks: 1.01,
  },
  {
    Player: 'Russell Westbrook',
    Position: 'PG',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 20,
    Points: 9.3,
    Assists: 3.8,
    Rebounds: 3.6,
    ThreePt: 0.72,
    Turnovers: 1.72,
    Steals: 0.8,
    Blocks: 0.3,
  },
  {
    Player: 'Mike Conley',
    Position: 'PG',
    Team: 'MIN',
    Opponent: 'DAL',
    Minutes: 25,
    Points: 9.3,
    Assists: 4.5,
    Rebounds: 2.4,
    ThreePt: 1.95,
    Turnovers: 1.15,
    Steals: 0.99,
    Blocks: 0.2,
  },
  {
    Player: 'Nicolas Claxton',
    Position: 'C',
    Team: 'BKN',
    Opponent: 'DEN',
    Minutes: 23,
    Points: 9.1,
    Assists: 2,
    Rebounds: 8.1,
    ThreePt: 0.02,
    Turnovers: 0.92,
    Steals: 0.54,
    Blocks: 1.61,
  },
  {
    Player: 'Walker Kessler',
    Position: 'C',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 28,
    Points: 9.1,
    Assists: 1.5,
    Rebounds: 9.1,
    ThreePt: 0.07,
    Turnovers: 0.98,
    Steals: 0.55,
    Blocks: 2.84,
  },
  {
    Player: 'Dorian Finney-Smith',
    Position: 'PF/SF',
    Team: 'BKN',
    Opponent: 'DEN',
    Minutes: 29,
    Points: 9,
    Assists: 2.1,
    Rebounds: 5.5,
    ThreePt: 1.72,
    Turnovers: 0.87,
    Steals: 0.76,
    Blocks: 0.55,
  },
  {
    Player: 'Draymond Green',
    Position: 'PF/C',
    Team: 'GSW',
    Opponent: 'NOP',
    Minutes: 28,
    Points: 8.6,
    Assists: 5.8,
    Rebounds: 6,
    ThreePt: 1,
    Turnovers: 2.96,
    Steals: 0.97,
    Blocks: 0.8,
  },
  {
    Player: 'Ziaire Williams',
    Position: 'SF',
    Team: 'BKN',
    Opponent: 'DEN',
    Minutes: 21.5,
    Points: 8.3,
    Assists: 1.4,
    Rebounds: 3.5,
    ThreePt: 1.08,
    Turnovers: 1.09,
    Steals: 0.61,
    Blocks: 0.21,
  },
  {
    Player: 'Dereck Lively II',
    Position: 'C',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 25.5,
    Points: 8.2,
    Assists: 1.8,
    Rebounds: 7.5,
    ThreePt: 0.01,
    Turnovers: 0.88,
    Steals: 0.81,
    Blocks: 1.44,
  },
  {
    Player: 'Daniel Gafford',
    Position: 'C',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 20.5,
    Points: 7.8,
    Assists: 1.2,
    Rebounds: 6,
    ThreePt: 0,
    Turnovers: 0.7,
    Steals: 0.68,
    Blocks: 1.46,
  },
  {
    Player: 'Julian Strawther',
    Position: 'SF',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 20,
    Points: 7.4,
    Assists: 1.4,
    Rebounds: 2.3,
    ThreePt: 1.39,
    Turnovers: 0.76,
    Steals: 0.56,
    Blocks: 0.27,
  },
  {
    Player: 'Nickeil Alexander-Walker',
    Position: 'SG/SF',
    Team: 'MIN',
    Opponent: 'DAL',
    Minutes: 20,
    Points: 7.1,
    Assists: 2.2,
    Rebounds: 2.1,
    ThreePt: 1.34,
    Turnovers: 0.83,
    Steals: 0.61,
    Blocks: 0.34,
  },
  {
    Player: 'Kyle Anderson',
    Position: 'PF/SF',
    Team: 'GSW',
    Opponent: 'NOP',
    Minutes: 19,
    Points: 6.7,
    Assists: 3.2,
    Rebounds: 3,
    ThreePt: 0.42,
    Turnovers: 1.07,
    Steals: 0.76,
    Blocks: 0.52,
  },
  {
    Player: 'Gary Payton II',
    Position: 'SG/PG',
    Team: 'GSW',
    Opponent: 'NOP',
    Minutes: 18,
    Points: 6.6,
    Assists: 1.5,
    Rebounds: 2.7,
    ThreePt: 0.67,
    Turnovers: 0.91,
    Steals: 1.1,
    Blocks: 0.31,
  },
  {
    Player: 'Trey Lyles',
    Position: 'PF/C',
    Team: 'SAC',
    Opponent: 'UTA',
    Minutes: 17,
    Points: 6.5,
    Assists: 0.9,
    Rebounds: 3.5,
    ThreePt: 1.32,
    Turnovers: 0.54,
    Steals: 0.38,
    Blocks: 0.34,
  },
  {
    Player: 'Yves Missi',
    Position: 'C',
    Team: 'NOP',
    Opponent: 'GSW',
    Minutes: 20,
    Points: 6,
    Assists: 1.1,
    Rebounds: 5.3,
    ThreePt: 0,
    Turnovers: 0.9,
    Steals: 0.47,
    Blocks: 1.43,
  },
  {
    Player: 'Jalen Wilson',
    Position: 'PF',
    Team: 'BKN',
    Opponent: 'DEN',
    Minutes: 20.5,
    Points: 6,
    Assists: 1.6,
    Rebounds: 3.7,
    ThreePt: 0.69,
    Turnovers: 0.77,
    Steals: 0.34,
    Blocks: 0.13,
  },
  {
    Player: 'Cody Williams',
    Position: 'SF',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 24,
    Points: 6,
    Assists: 1.5,
    Rebounds: 3.3,
    ThreePt: 0.66,
    Turnovers: 1.18,
    Steals: 0.59,
    Blocks: 0.42,
  },
  {
    Player: 'Brice Sensabaugh',
    Position: 'SF',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 15,
    Points: 5.9,
    Assists: 1.4,
    Rebounds: 2.6,
    ThreePt: 0.9,
    Turnovers: 1.12,
    Steals: 0.38,
    Blocks: 0.17,
  },
  {
    Player: 'Jose Alvarado',
    Position: 'PG',
    Team: 'NOP',
    Opponent: 'GSW',
    Minutes: 16.5,
    Points: 5.8,
    Assists: 2.8,
    Rebounds: 2,
    ThreePt: 1.16,
    Turnovers: 0.8,
    Steals: 0.95,
    Blocks: 0.19,
  },
  {
    Player: 'Kevon Looney',
    Position: 'C',
    Team: 'GSW',
    Opponent: 'NOP',
    Minutes: 19,
    Points: 5.8,
    Assists: 2,
    Rebounds: 6.8,
    ThreePt: 0,
    Turnovers: 0.84,
    Steals: 0.47,
    Blocks: 0.57,
  },
  {
    Player: 'Daniel Theis',
    Position: 'C',
    Team: 'NOP',
    Opponent: 'GSW',
    Minutes: 19.5,
    Points: 5.7,
    Assists: 1.3,
    Rebounds: 5.1,
    ThreePt: 0.51,
    Turnovers: 0.82,
    Steals: 0.42,
    Blocks: 0.92,
  },
  {
    Player: 'Javonte Green',
    Position: 'SF',
    Team: 'NOP',
    Opponent: 'GSW',
    Minutes: 18,
    Points: 5.6,
    Assists: 0.9,
    Rebounds: 4.3,
    ThreePt: 0.42,
    Turnovers: 0.65,
    Steals: 0.91,
    Blocks: 0.51,
  },
  {
    Player: 'Lindy Waters III',
    Position: 'SG',
    Team: 'GSW',
    Opponent: 'NOP',
    Minutes: 12.5,
    Points: 5.5,
    Assists: 0.8,
    Rebounds: 1.6,
    ThreePt: 1.58,
    Turnovers: 0.4,
    Steals: 0.35,
    Blocks: 0.22,
  },
  {
    Player: 'Peyton Watson',
    Position: 'PF',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 16,
    Points: 5.3,
    Assists: 0.9,
    Rebounds: 2.7,
    ThreePt: 0.46,
    Turnovers: 0.59,
    Steals: 0.39,
    Blocks: 0.93,
  },
  {
    Player: 'Naji Marshall',
    Position: 'SF',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 16.5,
    Points: 4.9,
    Assists: 1.5,
    Rebounds: 2.9,
    ThreePt: 0.55,
    Turnovers: 0.72,
    Steals: 0.56,
    Blocks: 0.17,
  },
  {
    Player: 'Kyle Filipowski',
    Position: 'PF',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 12.5,
    Points: 4.7,
    Assists: 1.3,
    Rebounds: 3.2,
    ThreePt: 0.42,
    Turnovers: 0.84,
    Steals: 0.29,
    Blocks: 0.43,
  },
  {
    Player: 'Spencer Dinwiddie',
    Position: 'PG',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 17.5,
    Points: 4.6,
    Assists: 2.1,
    Rebounds: 1.6,
    ThreePt: 0.76,
    Turnovers: 0.73,
    Steals: 0.44,
    Blocks: 0.14,
  },
  {
    Player: 'Quentin Grimes',
    Position: 'SG',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 14,
    Points: 4.5,
    Assists: 0.7,
    Rebounds: 1.6,
    ThreePt: 0.99,
    Turnovers: 0.44,
    Steals: 0.41,
    Blocks: 0.12,
  },
  {
    Player: 'Keon Johnson',
    Position: 'SG',
    Team: 'BKN',
    Opponent: 'DEN',
    Minutes: 10.5,
    Points: 4.3,
    Assists: 1.4,
    Rebounds: 1.2,
    ThreePt: 0.66,
    Turnovers: 0.64,
    Steals: 0.34,
    Blocks: 0.15,
  },
  {
    Player: 'Shake Milton',
    Position: 'PG',
    Team: 'BKN',
    Opponent: 'DEN',
    Minutes: 10.5,
    Points: 4.2,
    Assists: 1.4,
    Rebounds: 1.3,
    ThreePt: 0.43,
    Turnovers: 0.48,
    Steals: 0.24,
    Blocks: 0.11,
  },
  {
    Player: 'Jaden Hardy',
    Position: 'SG',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 9,
    Points: 3.9,
    Assists: 0.7,
    Rebounds: 1.1,
    ThreePt: 0.64,
    Turnovers: 0.58,
    Steals: 0.22,
    Blocks: 0.06,
  },
  {
    Player: 'Keon Ellis',
    Position: 'SG/PG',
    Team: 'SAC',
    Opponent: 'UTA',
    Minutes: 13,
    Points: 3.6,
    Assists: 1,
    Rebounds: 1.8,
    ThreePt: 0.95,
    Turnovers: 0.41,
    Steals: 0.73,
    Blocks: 0.37,
  },
  {
    Player: 'Johnny Juzang',
    Position: 'SF',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 9,
    Points: 3.4,
    Assists: 0.5,
    Rebounds: 1,
    ThreePt: 0.75,
    Turnovers: 0.28,
    Steals: 0.13,
    Blocks: 0.07,
  },
  {
    Player: 'Dario Saric',
    Position: 'PF/C',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 9,
    Points: 3.2,
    Assists: 1,
    Rebounds: 1.9,
    ThreePt: 0.38,
    Turnovers: 0.54,
    Steals: 0.23,
    Blocks: 0.08,
  },
  {
    Player: 'Patty Mills',
    Position: 'PG',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 9,
    Points: 3.2,
    Assists: 0.9,
    Rebounds: 0.7,
    ThreePt: 0.64,
    Turnovers: 0.33,
    Steals: 0.26,
    Blocks: 0.04,
  },
  {
    Player: 'Alex Len',
    Position: 'C',
    Team: 'SAC',
    Opponent: 'UTA',
    Minutes: 9,
    Points: 2.5,
    Assists: 0.7,
    Rebounds: 2.6,
    ThreePt: 0.03,
    Turnovers: 0.45,
    Steals: 0.2,
    Blocks: 0.61,
  },
  {
    Player: 'Gui Santos',
    Position: 'PF',
    Team: 'GSW',
    Opponent: 'NOP',
    Minutes: 6,
    Points: 2.4,
    Assists: 0.4,
    Rebounds: 1.3,
    ThreePt: 0.28,
    Turnovers: 0.31,
    Steals: 0.14,
    Blocks: 0.11,
  },
  {
    Player: 'Joe Ingles',
    Position: 'SG',
    Team: 'MIN',
    Opponent: 'DAL',
    Minutes: 6.5,
    Points: 1.6,
    Assists: 1.2,
    Rebounds: 0.8,
    ThreePt: 0.4,
    Turnovers: 0.32,
    Steals: 0.19,
    Blocks: 0.04,
  },
  {
    Player: 'Doug McDermott',
    Position: 'PF',
    Team: 'SAC',
    Opponent: 'UTA',
    Minutes: 4,
    Points: 1.5,
    Assists: 0.3,
    Rebounds: 0.3,
    ThreePt: 0.41,
    Turnovers: 0.12,
    Steals: 0.06,
    Blocks: 0.02,
  },
  {
    Player: 'Olivier-Maxence Prosper',
    Position: 'PF',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 4,
    Points: 1.1,
    Assists: 0.2,
    Rebounds: 0.9,
    ThreePt: 0.12,
    Turnovers: 0.13,
    Steals: 0.1,
    Blocks: 0.03,
  },
  {
    Player: 'Jordan McLaughlin',
    Position: 'PG',
    Team: 'SAC',
    Opponent: 'UTA',
    Minutes: 3,
    Points: 0.8,
    Assists: 0.5,
    Rebounds: 0.3,
    ThreePt: 0.16,
    Turnovers: 0.1,
    Steals: 0.17,
    Blocks: 0.03,
  },
  {
    Player: 'Jeremiah Robinson-Earl',
    Position: 'C',
    Team: 'NOP',
    Opponent: 'GSW',
    Minutes: 2,
    Points: 0.7,
    Assists: 0.1,
    Rebounds: 0.5,
    ThreePt: 0.1,
    Turnovers: 0.08,
    Steals: 0.06,
    Blocks: 0.03,
  },
  {
    Player: 'Josh Minott',
    Position: 'SF',
    Team: 'MIN',
    Opponent: 'DAL',
    Minutes: 1.5,
    Points: 0.6,
    Assists: 0.1,
    Rebounds: 0.3,
    ThreePt: 0.04,
    Turnovers: 0.06,
    Steals: 0.05,
    Blocks: 0.04,
  },
  {
    Player: 'Zeke Nnaji',
    Position: 'C',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 1.5,
    Points: 0.5,
    Assists: 0.1,
    Rebounds: 0.3,
    ThreePt: 0.02,
    Turnovers: 0.06,
    Steals: 0.04,
    Blocks: 0.07,
  },
  {
    Player: 'Dwight Powell',
    Position: 'C',
    Team: 'DAL',
    Opponent: 'MIN',
    Minutes: 2,
    Points: 0.4,
    Assists: 0.2,
    Rebounds: 0.5,
    ThreePt: 0,
    Turnovers: 0.07,
    Steals: 0.07,
    Blocks: 0.04,
  },
  {
    Player: 'Vlatko Cancar',
    Position: 'SF',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 1.5,
    Points: 0.4,
    Assists: 0.1,
    Rebounds: 0.2,
    ThreePt: 0.05,
    Turnovers: 0.05,
    Steals: 0.03,
    Blocks: 0.02,
  },
  {
    Player: 'Eugene Omoruyi',
    Position: 'SF',
    Team: 'MIN',
    Opponent: 'DAL',
    Minutes: 1,
    Points: 0.4,
    Assists: 0.1,
    Rebounds: 0.2,
    ThreePt: 0.03,
    Turnovers: 0.05,
    Steals: 0.04,
    Blocks: 0.01,
  },
  {
    Player: 'Drew Eubanks',
    Position: 'C',
    Team: 'UTA',
    Opponent: 'SAC',
    Minutes: 1,
    Points: 0.3,
    Assists: 0.1,
    Rebounds: 0.3,
    ThreePt: 0,
    Turnovers: 0.04,
    Steals: 0.02,
    Blocks: 0.06,
  },
  {
    Player: 'Jalen Pickett',
    Position: 'SG',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 1,
    Points: 0.3,
    Assists: 0.1,
    Rebounds: 0.1,
    ThreePt: 0.07,
    Turnovers: 0.06,
    Steals: 0.03,
    Blocks: 0.01,
  },
  {
    Player: 'Hunter Tyson',
    Position: 'SF',
    Team: 'DEN',
    Opponent: 'BKN',
    Minutes: 1,
    Points: 0.3,
    Assists: 0.1,
    Rebounds: 0.2,
    ThreePt: 0.05,
    Turnovers: 0.03,
    Steals: 0.02,
    Blocks: 0.01,
  },
];

const storage = createStorage<BackgroundData>(
  'background-storage-key',
  { lastUpdate: Date.now(), counter: 0, etrProjections: ETR_COPY_PASTE, pickSixSlates: {} },
  {
    storageEnum: StorageEnum.Local,
    liveUpdate: true,
  },
);

export const backgroundStorage: BaseStorage<BackgroundData> = {
  ...storage,
};
